version: '{build}'

os: Visual Studio 2017

configuration:
  - Release
  - Debug

platform:
  - x86
  - x64

branches:
  except:
    - coverity_scan

install:
  - git submodule update --init --recursive

before_build:
  - if [%PLATFORM%]==[x86] (
      cmake -G "Visual Studio 15 2017" -DCMAKE_INSTALL_PREFIX="%P%" -DBUILD_TESTS=ON
    ) else (
      cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX="%P%" -DBUILD_TESTS=ON
    )

build:
  project: ALL_BUILD.vcxproj
  parallel: true
  verbosity: normal

test_script:
  - "%CONFIGURATION%\\test_sexp.exe"

# EOF #
